module.exports={
    PRODUCT_COLLECTION:'product',
    USER_COLLECTION:'USER',
    CATEGORY_COLLECTION:'CATEGORY',
    CART_COLLECTION:'CART',
    ORDER_COLLECTION:'ORDER',
    WHISHLIST_COLLECTION:'WHISHLIST',
    ADDRESS_COLLECTION:'ADDRESS',
    COUPON_COLLECTION:'COUPON',
    BANNER_COLLECTION:'BANNER',
    MESSAGE_COLLECTION:'MESSAGE',

}